#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
LLM_TRY v10.10.0 Internalized Knowledge Registry

A concept is considered INTERNALIZED only when a trusted teaching pair has
actually been consumed by /train and its fingerprint is present in the
learning-state checkpoint metadata.

This registry is derived from:
  - data/chat_history.jsonl
  - data/chat_learning_state.json

It is not a retrieval store for answers.  The stored teacher answer is retained
only for audit/provenance. Runtime answers for INTERNALIZED concepts are still
generated by the model and must pass the normal output gate.
"""

from __future__ import annotations

from dataclasses import dataclass
from collections import OrderedDict
import hashlib
import json
import re
from pathlib import Path
from typing import List


TRUSTED_SOURCES = {
    "chat-manual",
    "chat-approved",
    "chat-recovery",
    "semantic-sleep",
}


@dataclass(frozen=True)
class InternalizedRecord:
    concept: str
    question: str
    teacher_answer: str
    fingerprint: str
    source: str
    timestamp: str = ""


def normalize_pair_text(text: str) -> str:
    return " ".join(str(text).strip().split())


def pair_fingerprint(user: str, answer: str) -> str:
    payload = normalize_pair_text(user) + "\n" + normalize_pair_text(answer)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def extract_definition_focus(question: str) -> str:
    q = str(question).strip()

    patterns = (
        r"^\s*([^\s、。！？?]{1,40})\s*(?:とは|って何)\s*[、,。．！？!?？?]*\s*$",
        r"^\s*(.+?)\s*(?:について教えて|を説明して|を簡単に説明して)\s*$",
    )
    for pattern in patterns:
        match = re.fullmatch(pattern, q)
        if match:
            return match.group(1).strip()
    return ""


def load_trained_fingerprints(state_path: Path) -> set[str]:
    if not state_path.exists():
        return set()

    try:
        payload = json.loads(state_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return set()

    values = payload.get("trained_fingerprints", [])
    if not isinstance(values, list):
        return set()
    return {str(value) for value in values}


def load_internalized_records(
    learning_log: Path,
    learning_state: Path,
) -> List[InternalizedRecord]:
    trained = load_trained_fingerprints(learning_state)
    if not trained or not learning_log.exists():
        return []

    records: List[InternalizedRecord] = []
    seen = set()

    for raw in learning_log.read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue

        try:
            row = json.loads(raw)
        except json.JSONDecodeError:
            continue

        source = str(row.get("source", "")).strip()
        timestamp = str(row.get("timestamp", "")).strip()
        if source not in TRUSTED_SOURCES:
            continue

        question = str(row.get("user", "")).strip()
        answer = str(row.get("assistant", "")).strip()
        if not question or not answer:
            continue

        fingerprint = pair_fingerprint(question, answer)
        if fingerprint not in trained:
            continue

        concept = extract_definition_focus(question)
        if not concept:
            continue

        key = (concept.lower(), fingerprint)
        if key in seen:
            continue
        seen.add(key)

        records.append(
            InternalizedRecord(
                concept=concept,
                question=question,
                teacher_answer=answer,
                fingerprint=fingerprint,
                source=source,
                timestamp=timestamp,
            )
        )

    return records


def internalized_record_for_focus(
    records: List[InternalizedRecord],
    focus: str,
) -> InternalizedRecord | None:
    target = str(focus).strip().lower()
    if not target:
        return None

    matches = [
        record
        for record in records
        if record.concept.strip().lower() == target
    ]
    if not matches:
        return None

    # Prefer the most recent matching trusted row from the log-derived order.
    return matches[-1]


@dataclass(frozen=True)
class InternalizedConcept:
    concept: str
    latest_question: str
    latest_teacher_answer: str
    latest_source: str
    fingerprints: tuple[str, ...]
    sources: tuple[str, ...]
    trained_pairs: int
    latest_timestamp: str = ""


def consolidate_internalized_records(
    records: List[InternalizedRecord],
) -> List[InternalizedConcept]:
    """Group fingerprint-level evidence into one concept-level registry row."""
    grouped: "OrderedDict[str, List[InternalizedRecord]]" = OrderedDict()

    for record in records:
        key = record.concept.strip().lower()
        grouped.setdefault(key, []).append(record)

    concepts: List[InternalizedConcept] = []
    for rows in grouped.values():
        latest = rows[-1]

        fingerprints: List[str] = []
        sources: List[str] = []
        for row in rows:
            if row.fingerprint not in fingerprints:
                fingerprints.append(row.fingerprint)
            if row.source not in sources:
                sources.append(row.source)

        concepts.append(
            InternalizedConcept(
                concept=latest.concept,
                latest_question=latest.question,
                latest_teacher_answer=latest.teacher_answer,
                latest_source=latest.source,
                fingerprints=tuple(fingerprints),
                sources=tuple(sources),
                trained_pairs=len(fingerprints),
                latest_timestamp=latest.timestamp,
            )
        )

    return concepts


def load_internalized_concepts(
    learning_log: Path,
    learning_state: Path,
) -> List[InternalizedConcept]:
    return consolidate_internalized_records(
        load_internalized_records(
            learning_log,
            learning_state,
        )
    )


def internalized_concept_for_focus(
    concepts: List[InternalizedConcept],
    focus: str,
) -> InternalizedConcept | None:
    target = str(focus).strip().lower()
    if not target:
        return None

    for concept in concepts:
        if concept.concept.strip().lower() == target:
            return concept
    return None
